// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef AnimationUI_h
#define AnimationUI_h
#include "EditorIncl.h"
#include "EditorDef.h"
#include "Model.h"
#include <fltk/Window.h>
#include <fltk/Choice.h>
#include <fltk/Item.h>

class IK_UI  {
public:
  fltk::Window* CreateUI();
  fltk::Window *window;
    fltk::Choice *selJointType;
private:
      inline void cb_Fixed_i(fltk::Item*, void*);
      static void cb_Fixed(fltk::Item*, void*);
      inline void cb_Hinge_i(fltk::Item*, void*);
      static void cb_Hinge(fltk::Item*, void*);
      inline void cb_Universal_i(fltk::Item*, void*);
      static void cb_Universal(fltk::Item*, void*);
#include "IK_CB.h"
};
#include <fltk/ValueSlider.h>
#include <fltk/Button.h>
#include <fltk/CheckButton.h>

class TimelineUI  {
public:
  fltk::Window* CreateUI();
  fltk::Window *window;
    fltk::ValueSlider *timeSlider;
private:
    inline void cb_timeSlider_i(fltk::ValueSlider*, void*);
    static void cb_timeSlider(fltk::ValueSlider*, void*);
    inline void cb_Set_i(fltk::Button*, void*);
    static void cb_Set(fltk::Button*, void*);
public:
    fltk::Button *playstopButton;
private:
    inline void cb_playstopButton_i(fltk::Button*, void*);
    static void cb_playstopButton(fltk::Button*, void*);
    inline void cb_Pause_i(fltk::Button*, void*);
    static void cb_Pause(fltk::Button*, void*);
public:
    fltk::CheckButton *autoKeying;
private:
    inline void cb_Insert_i(fltk::Button*, void*);
    static void cb_Insert(fltk::Button*, void*);
#include "TimelineCB.h"
};
#include <fltk/TiledGroup.h>
#include "AnimKeyTrackView.h"
#include <fltk/MultiBrowser.h>
#include <fltk/Group.h>
#include <fltk/InvisibleBox.h>

class AnimTrackEditorUI  {
public:
  fltk::Window* CreateUI();
  fltk::Window *window;
      AnimKeyTrackView *trackView;
      fltk::MultiBrowser *propBrowser;
private:
      inline void cb_Auto_i(fltk::Button*, void*);
      static void cb_Auto(fltk::Button*, void*);
      inline void cb_Delete_i(fltk::Button*, void*);
      static void cb_Delete(fltk::Button*, void*);
      inline void cb_Move_i(fltk::CheckButton*, void*);
      static void cb_Move(fltk::CheckButton*, void*);
      inline void cb_Auto1_i(fltk::Button*, void*);
      static void cb_Auto1(fltk::Button*, void*);
public:
      fltk::CheckButton *chkLockObjects;
#include "AnimTrackEditorCB.h"
};
#endif
